In [1]:
from __future__ import print_function
from datetime import datetime
import pandas
import numpy

In [2]:
import sys
sys.path.append('../shifted_beta_survival/')

In [3]:
from DataHandler import DataHandler
from ShiftedBeta import ShiftedBeta
from ShiftedBetaSurvival import ShiftedBetaSurvival

In [4]:
from new_test import make_raw_article_data, print_stats

In [8]:
data = pandas.read_csv('../data/data_2yr.csv')

total_size = 1000
index = numpy.arange(data.shape[0])
numpy.random.shuffle(index)
index = index[:total_size]

data = data.iloc[index]
data.index = numpy.arange(total_size)

In [9]:
names = list(data.keys())[1:-2]

x = data[names].values
y = data.values[:, -2].astype(int)
z = data.values[:, -1].astype(int)

names = ['bias'] + names

In [10]:
sb = ShiftedBeta(verbose=True, gamma_alpha=1e1, gamma_beta=1e1)
sb.fit(y, z, x, restarts=1)

Starting Optimization with parameters:
        Samples: 1000
  gamma (alpha): 10.0
   gamma (beta): 10.0
           bias: True
          Seeds: 1

Step  |    Time    | LogLikelihood |
-----------------------------------
    1 | 0:00:10.53 |     1225.9183 |


In [11]:
print_stats(sb.alpha, sb.beta, [0], names)
for i in range(1, len(names)):
    print_stats(sb.alpha, sb.beta, [0, i], names)

bias_                | 0.85869, 40.714, 0.020655
bias_freshapp_       | 0.87873, 38.836, 0.022126
bias_mobile_         | 0.8447, 41.726, 0.019842
bias_fic_            | 0.85323, 41.668, 0.020066
bias_annual_         | 0.69648, 49.647, 0.013835
bias_monthly_        | 1.0514, 33.611, 0.030332
bias_is_contractor_  | 0.91307, 37.936, 0.023503
bias_creatives_      | 0.77034, 44.833, 0.016892
bias_trades_         | 0.90312, 38.292, 0.023041
bias_other_prof_     | 0.91039, 39.304, 0.022638


In [12]:
preds_coeff = sb.predict(x)
preds = data[['system_key']].copy()
preds['alpha'] = preds_coeff[:, 0]
preds['beta'] = preds_coeff[:, 1]
preds['churn'] = preds_coeff[:, 0] / (preds_coeff[:, 0] + preds_coeff[:, 1])

print(x[:20])
print(preds.iloc[:20])

[[1 0 0 1 0 0 0 1 0]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 1 0 0]
 [0 1 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 1 0 0]
 [1 0 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 0 1 0]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 1 0 0]
 [1 0 0 0 1 1 0 0 1]
 [1 0 0 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [1 0 0 0 1 0 0 1 0]
 [1 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 0 0 1]]
    system_key     alpha       beta     churn
0      1586202  0.749606  44.540352  0.016551
1      1072364  1.140694  30.950478  0.035545
2       664172  1.140694  30.950478  0.035545
3      1358151  0.755640  45.717211  0.016260
4      1460009  0.965216  35.303937  0.026613
5       564737  1.096516  33.253733  0.031922
6      1204236  1.140694  30.950478  0.035545
7      1542158  0.965216  35.303937  0.026613
8       277833  0.755640  45.717211  0.016260
9      1215776  1.140694  30.950478  0.035545
10     1134651  1.131585  30.153746  0.036170
11     1139862  1.140694  3

In [13]:
data.merge(preds, on='system_key').groupby('is_contractor').mean()[['churn']]

churn
is_contractor          
0              0.031109
1              0.035885

In [14]:
preds

system_key     alpha       beta     churn
0       1586202  0.749606  44.540352  0.016551
1       1072364  1.140694  30.950478  0.035545
2        664172  1.140694  30.950478  0.035545
3       1358151  0.755640  45.717211  0.016260
4       1460009  0.965216  35.303937  0.026613
5        564737  1.096516  33.253733  0.031922
6       1204236  1.140694  30.950478  0.035545
7       1542158  0.965216  35.303937  0.026613
8        277833  0.755640  45.717211  0.016260
9       1215776  1.140694  30.950478  0.035545
10      1134651  1.131585  30.153746  0.036170
11      1139862  1.140694  30.950478  0.035545
12      1384234  0.965216  35.303937  0.026613
13       990181  1.212922  28.838543  0.040361
14      1550693  0.755640  45.717211  0.016260
15       828666  1.140694  30.950478  0.035545
16      1104489  0.639397  52.147741  0.012113
17       781250  1.131585  30.153746  0.036170
18      1413924  1.140694  30.950478  0.035545
19      1113538  1.140694  30.950478  0.035545
20      1204137  1.140694  30.950478  0.035545
21       986849  1.140694  30.950478  0.035545
22       708106  1.140694  30.950478  0.035545
23      1235567  1.140694  30.950478  0.035545
24      1087249  1.140694  30.950478  0.035545
25       961847  1.140694  30.950478  0.035545
26      1529719  0.931633  37.491154  0.024247
27       825445  0.755640  45.717211  0.016260
28      1063513  1.107592  33.207616  0.032277
29       658099  0.965216  35.303937  0.026613
..          ...       ...        ...       ...
970      526548  1.140694  30.950478  0.035545
971     1307448  1.131585  30.153746  0.036170
972      681809  0.965216  35.303937  0.026613
973     1316910  1.140694  30.950478  0.035545
974      886648  0.755640  45.717211  0.016260
975      788221  0.965216  35.303937  0.026613
976     1303976  1.107592  33.207616  0.032277
977      836588  0.755640  45.717211  0.016260
978      959266  0.755640  45.717211  0.016260
979     1467856  1.096516  33.253733  0.031922
980      713223  1.140694  30.950478  0.035545
981     1077306  1.140694  30.950478  0.035545
982     1487361  1.140694  30.950478  0.035545
983      959370  1.140694  30.950478  0.035545
984      799430  1.107592  33.207616  0.032277
985     1060621  1.140694  30.950478  0.035545
986     1015618  1.140694  30.950478  0.035545
987     1026154  1.212922  28.838543  0.040361
988      681612  1.140694  30.950478  0.035545
989     1618695  0.924194  36.526051  0.024678
990      967091  0.931633  37.491154  0.024247
991      863219  0.755640  45.717211  0.016260
992      676355  1.140694  30.950478  0.035545
993     1379794  1.140694  30.950478  0.035545
994     1262579  1.140694  30.950478  0.035545
995     1073653  1.131585  30.153746  0.036170
996     1254416  0.965216  35.303937  0.026613
997      714687  1.140694  30.950478  0.035545
998     1410913  0.965216  35.303937  0.026613
999      965248  1.140694  30.950478  0.035545

[1000 rows x 4 columns]

In [32]:
data

system_key  freshapp  mobile  fic  annual  monthly  is_contractor  \
0          359159         1       0    0       0        1              0   
1          826716         1       0    0       0        1              0   
2          783875         1       0    0       0        1              0   
3         1543315         1       0    0       1        0              0   
4         1083580         1       0    0       0        1              0   
5          472560         1       0    0       0        1              0   
6         1182744         1       0    0       1        0              0   
7          701410         1       0    0       0        1              0   
8          547422         1       0    0       0        1              0   
9          925671         0       1    0       0        1              0   
10         844252         1       0    0       1        0              0   
11        1247248         1       0    0       0        1              0   
12         963393         1       0    0       0        1              0   
13        1351967         1       0    0       0        1              0   
14         730891         1       0    0       0        1              0   
15         681741         1       0    0       0        1              0   
16         965223         1       0    0       0        1              0   
17         826820         1       0    0       0        1              0   
18        1135651         1       0    0       0        1              0   
19        1535303         1       0    0       0        1              0   
20         703504         1       0    0       0        1              0   
21         378527         1       0    0       0        1              0   
22         950125         1       0    0       1        0              0   
23         696377         1       0    0       1        0              0   
24        1059761         1       0    0       0        1              0   
25         983032         1       0    0       0        1              0   
26         839769         1       0    0       0        1              0   
27        1400445         1       0    0       0        1              0   
28        1420382         1       0    0       0        1              0   
29         746381         1       0    0       0        1              0   
...           ...       ...     ...  ...     ...      ...            ...   
62864     1357613         1       0    0       0        1              0   
62865      695220         1       0    0       0        1              0   
62866      885496         1       0    0       0        1              0   
62867     1075211         1       0    0       0        1              0   
62868     1338120         1       0    0       0        1              0   
62869      862973         1       0    0       0        1              0   
62870     1194953         1       0    0       0        1              0   
62871      403573         1       0    0       0        1              0   
62872      914120         1       0    0       1        0              0   
62873      684184         1       0    0       0        1              0   
62874      769266         1       0    0       0        1              0   
62875     1038798         1       0    0       0        1              0   
62876      862630         1       0    0       0        1              0   
62877     1545595         1       0    0       0        1              0   
62878     1192198         1       0    0       0        1              0   
62879     1127789         1       0    0       0        1              0   
62880      740962         1       0    0       1        0              0   
62881      940221         1       0    0       0        1              0   
62882     1315165         1       0    0       0        1              0   
62883      707864         1       0    0       0        1              0   
62884      673061         1       0    0       0       